version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5

    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go test ./...
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"
