version: 2.1

jobs:
  test_go112:
    docker:
      - image: circleci/golang:1.12.9

    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go test ./...
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"

  test_go113:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go test ./...
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  default:
    jobs:
      - test_go112
      - test_go113
